baseURL = "https://shineq-cherry.github.io/"
title = "我的 Hugo 博客"
theme = "hugo-theme-stack"  # 你的主题名称
languageCode = "zh-cn"  # 语言
defaultContentLanguage = "zh"
enableRobotsTXT = true  # 允许搜索引擎索引

# ✅ Hugo 0.128.0 之后，`paginate` 被移除，必须使用 `pagination.pagerSize`
[pagination]
  pagerSize = 5

# ✅ 作者信息（`author.email` 不能是字符串，必须在 `params.author` 里）
[params]
  description = "一个使用 Hugo Stack 主题的博客"
  defaultTheme = "light"  # 主题模式，可选 "dark"
  mainSections = ["posts"]  # 主要内容目录
  [params.author]
    name = "你的名字"
    email = "your-email@example.com"  # 这里必须放在 `params.author` 里

# ✅ 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 3

# ✅ 代码高亮
[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true
    lineNos = true
    style = "dracula"

